- name: Install and configure Nginx
  hosts: webservers
  become: yes
  vars:
    nginx_conf_template: /etc/nginx/nginx.conf
    server_name: example.com
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create Nginx configuration file from template
      template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_conf_template }}"
      notify:
        - restart nginx

    - name: Ensure firewall allows HTTP and HTTPS traffic
      ufw:
        rule: allow
        name: "Open port 80 and 443"
        port: "80,443"
        proto: tcp

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted